CEREBRAS_API_KEY="csk-fjvcew6t9x59tx6d55r4cjypjpepe8cwfhrxh5kcpr52c2ep"
OPENAI_API_KEY="64ca30f47c6e47439ffb6c268e1dc505"
UPSTAGE_API_KEY="up_yc3wCATmc7itK6fGspKvpvR6igjP2"
CEREBRAS_API_BASE="https://api.cerebras.ai/v1"
OPENAI_API_BASE="https://api.aimlapi.com"
CEREBRAS_MODEL="llama3.1-70b"
OPENAI_MODEL="o1-preview"